# Generated by Django 3.1.3 on 2020-11-29 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applict', '0003_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='sitename',
            new_name='project_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='date_posted',
        ),
    ]
