# Generated by Django 3.1.3 on 2020-11-29 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applict', '0006_auto_20201130_0056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='content_rating',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='design_rating',
            new_name='design',
        ),
    ]
